# Generated by Django 4.0.2 on 2022-03-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
