# Generated by Django 4.0.2 on 2022-03-12 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_temperature_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidity',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 34, 27, 510528)),
        ),
        migrations.AddField(
            model_name='temperature',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 12, 11, 34, 27, 510204)),
        ),
    ]
